Build Multistage

diff --git a/.github/workflows/images-architecture.yml b/.github/workflows/images-architecture.yml
--- a/.github/workflows/images-architecture.yml
+++ b/.github/workflows/images-architecture.yml
@@ -24,7 +24,7 @@ jobs:
         uses: docker/setup-buildx-action@v2
 
       - name: Build contexts
-        run: docker buildx ls  # Check available platforms
+        run: docker buildx ls 
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -37,15 +37,27 @@ jobs:
           docker buildx build --platform linux/${{ matrix.architecture }} \
             -t skhtskiryna/my-http-server:${{ matrix.architecture }} --push .
 
-      # Ensure both images are built before creating the manifest
-      - name: Create and push multi-architecture manifest
-        if: ${{ matrix.architecture == 'arm64' }}  # Only create manifest once arm64 is built
+      # Wait for both amd64 and arm64 images to be available on Docker Hub
+      - name: Check if amd64 image is available
         run: |
-          # Wait for both amd64 and arm64 images to be available on Docker Hub
-          echo "Waiting for both images to be available on Docker Hub..."
-          sleep 30  # Adjust sleep time if needed
+          docker pull skhtskiryna/my-http-server:amd64 || echo "amd64 image not found"
 
-          # Create a multi-architecture manifest that includes both images
+      - name: Check if arm64 image is available
+        run: |
+          docker pull skhtskiryna/my-http-server:arm64 || echo "arm64 image not found"
+
+      # Wait for both amd64 and arm64 images to be available on Docker Hub
+      - name: Wait for both images to be available on Docker Hub
+        if: ${{ matrix.architecture == 'arm64' }}
+        run: |
+          echo "Waiting for both images to be available on Docker Hub..."
+          sleep 30  # За потреби налаштуйте час затримки
+
+      # Create and push multi-architecture manifest
+      - name: Create and push multi-architecture manifest
+        if: ${{ matrix.architecture == 'arm64' }}  
+        run: |
+          # Create a multi-architecture manifest
           docker manifest create skhtskiryna/my-http-server:latest \
             --amend skhtskiryna/my-http-server:amd64 \
             --amend skhtskiryna/my-http-server:arm64
